spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://3.87.90.191:10000/auth/realms/famille
  datasource:
    url: jdbc:postgresql://famille-db:5432/postgres
    username: postgres
    password: famille
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      group-id: chat-group-id
      auto-offset-reset: earliest
    bootstrap-servers: 3.87.90.191:9094
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

producer:
  kafka:
    topic-name: chat-famille
    topic-name-intervention: intervention-app

nounou:
  application:
    url: "http://int.certification-tests.com:8080"

javamelody:
  init-parameters:
    log: true
    url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    authorized-users: admin:pwd
    storage-directory: /tmp/javamelody
    monitoring-path: /monitoring

server:
  port: 8081