spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
  kafka:
    consumer:
      group-id: chat-group-id
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

nounou:
  application:
    url: "http://int.certification-tests.com:8080"